# Generated by Django 4.1.5 on 2023-01-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email_address',
            field=models.EmailField(default='abc123@abc.com', max_length=254),
        ),
    ]
